name: Build Executables for Windows and Linux

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build on Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: pyinstaller --onefile --name libretranslateGUI.exe main.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executable
          path: dist/libretranslateGUI.exe

  # Build on Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux Executable
        run: pyinstaller --onefile --name libretranslateGUI main.py

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v3
        with:
          name: Linux-Executable
          path: dist/libretranslateGUI
